package com.gt.poputar;

/* This class is generated by JADX */
public final class R {

    public static final class drawable {
        public static final int app_banner = 2130837504;
        public static final int app_icon = 2130837505;
        public static final int com_facebook_close = 2130837506;
        public static final int umeng_socialize_back_icon = 2130837507;
        public static final int umeng_socialize_btn_bg = 2130837508;
        public static final int umeng_socialize_copy = 2130837509;
        public static final int umeng_socialize_copyurl = 2130837510;
        public static final int umeng_socialize_delete = 2130837511;
        public static final int umeng_socialize_edit_bg = 2130837512;
        public static final int umeng_socialize_facebook = 2130837513;
        public static final int umeng_socialize_fav = 2130837514;
        public static final int umeng_socialize_fbmessage = 2130837515;
        public static final int umeng_socialize_menu_default = 2130837516;
        public static final int umeng_socialize_more = 2130837517;
        public static final int umeng_socialize_qq = 2130837518;
        public static final int umeng_socialize_qzone = 2130837519;
        public static final int umeng_socialize_share_music = 2130837520;
        public static final int umeng_socialize_share_video = 2130837521;
        public static final int umeng_socialize_share_web = 2130837522;
        public static final int umeng_socialize_sina = 2130837523;
        public static final int umeng_socialize_twitter = 2130837524;
        public static final int umeng_socialize_wechat = 2130837525;
        public static final int umeng_socialize_wxcircle = 2130837526;
        public static final int unity_static_splash = 2130837527;
    }

    public static final class layout {
        public static final int com_facebook_activity_layout = 2130903040;
        public static final int com_facebook_login_fragment = 2130903041;
        public static final int socialize_share_menu_item = 2130903042;
        public static final int umeng_socialize_oauth_dialog = 2130903043;
        public static final int umeng_socialize_share = 2130903044;
    }

    public static final class string {
        public static final int com_facebook_like_button_not_liked = 2130968576;
        public static final int com_facebook_like_button_liked = 2130968577;
        public static final int com_facebook_loginview_log_out_button = 2130968578;
        public static final int com_facebook_loginview_log_in_button = 2130968579;
        public static final int com_facebook_loginview_log_in_button_long = 2130968580;
        public static final int com_facebook_loginview_logged_in_as = 2130968581;
        public static final int com_facebook_loginview_logged_in_using_facebook = 2130968582;
        public static final int com_facebook_loginview_log_out_action = 2130968583;
        public static final int com_facebook_loginview_cancel_action = 2130968584;
        public static final int com_facebook_loading = 2130968585;
        public static final int com_facebook_internet_permission_error_title = 2130968586;
        public static final int com_facebook_internet_permission_error_message = 2130968587;
        public static final int com_facebook_tooltip_default = 2130968588;
        public static final int com_facebook_image_download_unknown_error = 2130968589;
        public static final int com_facebook_share_button_text = 2130968590;
        public static final int com_facebook_send_button_text = 2130968591;
        public static final int messenger_send_button_text = 2130968592;
        public static final int app_name = 2130968593;
        public static final int facebook_app_id = 2130968594;
        public static final int com_facebook_dialogloginactivity_ok_button = 2130968595;
        public static final int com_facebook_requesterror_password_changed = 2130968596;
        public static final int com_facebook_requesterror_reconnect = 2130968597;
        public static final int com_facebook_requesterror_permissions = 2130968598;
        public static final int umeng_socialize_sharetosina = 2130968599;
        public static final int umeng_socialize_sharetodouban = 2130968600;
        public static final int umeng_socialize_sharetorenren = 2130968601;
        public static final int umeng_socialize_sharetotencent = 2130968602;
        public static final int umeng_socialize_sharetotwitter = 2130968603;
        public static final int umeng_socialize_sharetolinkin = 2130968604;
        public static final int umeng_socialize_text_tencent_key = 2130968605;
        public static final int umeng_socialize_text_wenxin_fav = 2130968606;
        public static final int umeng_socialize_text_sina_key = 2130968607;
        public static final int umeng_socialize_text_qq_key = 2130968608;
        public static final int umeng_socialize_text_qq_zone_key = 2130968609;
        public static final int umeng_socialize_text_renren_key = 2130968610;
        public static final int umeng_socialize_text_douban_key = 2130968611;
        public static final int umeng_socialize_text_weixin_key = 2130968612;
        public static final int umeng_socialize_text_weixin_circle_key = 2130968613;
        public static final int umeng_socialize_text_weixin_fav_key = 2130968614;
        public static final int umeng_socialize_text_add_custom_platform = 2130968615;
        public static final int umeng_example_home_btn_plus = 2130968616;
        public static final int umeng_socialize_text_waitting_share = 2130968617;
        public static final int umeng_socialize_content_hint = 2130968618;
        public static final int umeng_socialize_cancel_btn_str = 2130968619;
        public static final int umeng_socialize_send_btn_str = 2130968620;
        public static final int umeng_socialize_female = 2130968621;
        public static final int umeng_socialize_male = 2130968622;
        public static final int umeng_socialize_share = 2130968623;
        public static final int umeng_socialize_mail = 2130968624;
        public static final int umeng_socialize_sms = 2130968625;
        public static final int umeng_socialize_sina = 2130968626;
        public static final int umeng_socialize_text_yixin_key = 2130968627;
        public static final int umeng_socialize_text_yixincircle_key = 2130968628;
        public static final int umeng_socialize_text_laiwangdynamic_key = 2130968629;
        public static final int umeng_socialize_text_evernote_key = 2130968630;
        public static final int umeng_socialize_text_ydnote_key = 2130968631;
        public static final int umeng_socialize_text_facebook_key = 2130968632;
        public static final int umeng_socialize_text_facebookmessager_key = 2130968633;
        public static final int umeng_socialize_text_twitter_key = 2130968634;
        public static final int umeng_socialize_text_instagram_key = 2130968635;
        public static final int umeng_socialize_text_pinterest_key = 2130968636;
        public static final int umeng_socialize_text_pocket_key = 2130968637;
        public static final int umeng_socialize_text_linkedin_key = 2130968638;
        public static final int umeng_socialize_text_foursquare_key = 2130968639;
        public static final int umeng_socialize_text_whatsapp_key = 2130968640;
        public static final int umeng_socialize_text_line_key = 2130968641;
        public static final int umeng_socialize_text_flickr_key = 2130968642;
        public static final int umeng_socialize_text_tumblr_key = 2130968643;
        public static final int umeng_socialize_text_alipay_key = 2130968644;
        public static final int umeng_socialize_text_kakao_key = 2130968645;
        public static final int umeng_socialize_text_googleplus_key = 2130968646;
        public static final int umeng_socialize_text_more_key = 2130968647;
        public static final int umeng_socialize_text_dingding_key = 2130968648;
        public static final int umeng_socialize_text_vkontakte_key = 2130968649;
        public static final int umeng_socialize_text_dropbox_key = 2130968650;
    }

    public static final class style {
        public static final int UnityThemeSelector = 2131034112;
        public static final int ACPLDialog = 2131034113;
        public static final int umeng_socialize_action_bar_itemlayout = 2131034114;
        public static final int umeng_socialize_action_bar_item_im = 2131034115;
        public static final int umeng_socialize_action_bar_item_tv = 2131034116;
        public static final int umeng_socialize_popup_dialog = 2131034117;
        public static final int Theme_UMDialog = 2131034118;
        public static final int Theme_UMDefault = 2131034119;
        public static final int umeng_socialize_divider = 2131034120;
        public static final int umeng_socialize_list_item = 2131034121;
        public static final int umeng_socialize_edit_padding = 2131034122;
    }

    public static final class color {
        public static final int umeng_socialize_comments_bg = 2131099648;
        public static final int umeng_socialize_color_group = 2131099649;
        public static final int umeng_socialize_list_item_textcolor = 2131099650;
        public static final int umeng_socialize_list_item_bgcolor = 2131099651;
        public static final int umeng_socialize_divider = 2131099652;
        public static final int umeng_socialize_text_time = 2131099653;
        public static final int umeng_socialize_text_title = 2131099654;
        public static final int umeng_socialize_text_friends_list = 2131099655;
        public static final int umeng_socialize_text_share_content = 2131099656;
        public static final int umeng_socialize_ucenter_bg = 2131099657;
        public static final int umeng_socialize_text_ucenter = 2131099658;
        public static final int umeng_socialize_edit_bg = 2131099659;
        public static final int umeng_socialize_grid_divider_line = 2131099660;
        public static final int umeng_socialize_web_bg = 2131099661;
        public static final int umeng_socialize_shareactivity = 2131099662;
        public static final int umeng_socialize_shareactivitydefault = 2131099663;
    }

    public static final class dimen {
        public static final int alphabet_size = 2131165184;
        public static final int umeng_socialize_pad_window_height = 2131165185;
        public static final int umeng_socialize_pad_window_width = 2131165186;
    }

    public static final class id {
        public static final int com_facebook_fragment_container = 2131230720;
        public static final int com_facebook_login_activity_progress_bar = 2131230721;
        public static final int socialize_image_view = 2131230722;
        public static final int socialize_text_view = 2131230723;
        public static final int umeng_socialize_titlebar = 2131230724;
        public static final int umeng_title = 2131230725;
        public static final int umeng_back = 2131230726;
        public static final int umeng_share_btn = 2131230727;
        public static final int umeng_socialize_follow = 2131230728;
        public static final int umeng_socialize_follow_check = 2131230729;
        public static final int webView = 2131230730;
        public static final int progress_bar_parent = 2131230731;
        public static final int root = 2131230732;
        public static final int umeng_socialize_share_titlebar = 2131230733;
        public static final int umeng_socialize_share_edittext = 2131230734;
        public static final int umeng_socialize_share_word_num = 2131230735;
        public static final int umeng_socialize_share_bottom_area = 2131230736;
        public static final int umeng_image_edge = 2131230737;
        public static final int umeng_share_icon = 2131230738;
        public static final int umeng_web_title = 2131230739;
        public static final int umeng_del = 2131230740;
    }
}
